[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
    "pants.backend.experimental.codegen.protobuf.go",
    "pants.backend.experimental.go",
]
use_deprecated_directory_cli_args_semantics = false
use_deprecated_pex_binary_run_semantics = false

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["/"]

[golang]
minimum_expected_version = "1.18"
